#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FreeClub.Resource", IsApplication=true)]

namespace FreeClub
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int direction = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Events = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hist = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logofreed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logout = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int retour = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int share = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int vote = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int EmailTxt = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int IB1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int IB2 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int IB3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int IB4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int IB5 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int IB6 = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int MyBut = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int MyList = 2131034125;
			
			// aapt resource value: 0x7f050020
			public const int NoBut = 2131034144;
			
			// aapt resource value: 0x7f050013
			public const int but3Mois = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int butMois = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int butannée = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int connbut = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int date = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int description = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int image = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int imageView1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int layoutBase = 2131034134;
			
			// aapt resource value: 0x7f05000a
			public const int lien = 2131034122;
			
			// aapt resource value: 0x7f050023
			public const int listView = 2131034147;
			
			// aapt resource value: 0x7f050005
			public const int motPass = 2131034117;
			
			// aapt resource value: 0x7f05001b
			public const int myBut = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int myButton = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int myImage = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int mySpin = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int myVideo = 2131034141;
			
			// aapt resource value: 0x7f050024
			public const int mylistView = 2131034148;
			
			// aapt resource value: 0x7f050007
			public const int name = 2131034119;
			
			// aapt resource value: 0x7f05001e
			public const int nbPart = 2131034142;
			
			// aapt resource value: 0x7f050004
			public const int oubliTxt = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int passwordTxt = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050022
			public const int txt = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int video = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int yesBut = 2131034143;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Auth = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Events = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int history = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Home = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Images = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Partage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int partageImage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PartageVideo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int userRow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Videos = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Vote = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int VoteProject = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
